{{- if and .Values.persistence.enabled  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "profiler.fullname" . }}-data
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}