apiVersion: v1
kind: Service
metadata:
  name: {{ include "profiler.fullname" . }}
  labels:
    {{- include "profiler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: 80
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: 8080
  selector:
    {{- include "profiler.selectorLabels" . | nindent 4 }}
