apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profiler-data
  namespace: profiler-system
spec:
  storageClassName: alicloud-disk-ssd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi