name: Deployment

concurrency: development

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
        default: ''

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get the version
        id: get_version
        run: |
          echo $GITHUB_EVENT_NAME

          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            VERSION=${{ github.event.inputs.version }}
          fi

          if [[ $GITHUB_EVENT_NAME == "release" ]]; then
            VERSION=${{ github.event.release.tag_name }}
          fi
          echo ::set-output name=VERSION::${VERSION}
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/profiler profiler=xyctruth/profiler:${{ steps.get_version.outputs.VERSION }}  -n profiler-system
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/profiler -n profiler-system