name: Deployment

concurrency: development

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
        default: ''

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Get the version
        id: get_version
        run: |
          echo $GITHUB_EVENT_NAME

          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            VERSION=${{ github.event.inputs.version }}
          fi

          if [[ $GITHUB_EVENT_NAME == "release" ]]; then
            VERSION=${{ github.event.release.tag_name }}
          fi
          echo ::set-output name=VERSION::${VERSION}
      # TODO 修改为使用 Helm 部署应用程序
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'profiler-dev'
          namespace: 'profiler-system'
          chart: 'profiler'
          token: '${{ github.token }}'
          values: |
            image.tag: ${{ steps.get_version.outputs.VERSION }}
          value-files: "values.dev.yaml"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG_DATA }}'
