name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       make docker-build IMG=xyctruth/profiler:latest
    - name: Push the Docker image
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        docker login --username=xyctruth --password=${{ secrets.DOCKER_TOKEN }}
        make docker-push IMG=xyctruth/profiler:latest

