name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker image
        run: |
          docker build -t xyctruth/profiler:latest .
          docker tag xyctruth/profiler:latest xyctruth/profiler:${GITHUB_REF##refs/tags/}
          docker login --username=xyctruth --password=${{ secrets.DOCKER_TOKEN }}
          docker push xyctruth/profiler:latest
          docker push xyctruth/profiler:${GITHUB_REF##refs/tags/}