name: Server-Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "./charts/**"
      - "./ui/**"
      - "**.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "./charts/**"
      - "**.md"
      - "./ui/**"

jobs:
  server-build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v3

      - name: go mod package cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-1.17-${{ hashFiles('tests/go.mod') }}

      - name: Build
        run: |
          go build -v -race -a -o profiler ./server/main.go
  
